import type { Product } from './types';

// This catalogue mirrors the seed data in supabase/schema.sql.
// It is used as a fallback when the DB is not yet seeded, and for instant page loads.
// The source of truth in production is the Supabase `products` table.

export const CATALOGUE: Omit<Product, 'id' | 'created_at'>[] = [
  {
    slug: 'green-gummies',
    name: 'Green Gummies',
    category: 'Wellness',
    tagline: 'Nourish naturally with leafy-green goodness',
    description: 'A daily dose of kale and spirulina in a delicious gummy. Built for immune support, digestive health, and gentle recovery.',
    price_cents: 2499,
    compare_at_cents: 2999,
    currency: 'usd',
    image_url: '/products/green-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Immune Support', 'Digestive Health', 'Recovery'],
    ingredients: 'Kale extract, spirulina, organic cane sugar, tapioca syrup, pectin, citric acid, natural flavors.',
    suggested_use: 'Take 2 gummies daily with or without food.',
  },
  {
    slug: 'spirulina-daily-greens',
    name: 'Spirulina Daily Greens',
    category: 'Wellness',
    tagline: 'Your daily greens, reimagined',
    description: 'Spirulina, wheatgrass, and moringa packed into a single gummy. Designed for energy, detox and digestion.',
    price_cents: 2699,
    compare_at_cents: 3199,
    currency: 'usd',
    image_url: '/products/spirulina-daily-greens.png',
    stock: 100,
    active: true,
    benefits: ['Digestive Health', 'Energy Boost', 'Detox Support'],
    ingredients: 'Spirulina powder, wheatgrass, moringa leaf, organic cane sugar, pectin, natural lemon flavor.',
    suggested_use: 'Take 2 gummies daily, preferably in the morning.',
  },
  {
    slug: 'melatonin-sleep-well',
    name: 'Melatonin Sleep Well',
    category: 'Sleep',
    tagline: 'Drift off the natural way',
    description: 'A gentle melatonin blend with chamomile and L-theanine for deeper rest and smooth mornings.',
    price_cents: 2299,
    compare_at_cents: 2799,
    currency: 'usd',
    image_url: '/products/melatonin-sleep-well.png',
    stock: 100,
    active: true,
    benefits: ['Sleep Quality', 'Refreshed', 'Recovery'],
    ingredients: 'Melatonin (3mg), chamomile extract, L-theanine, passionflower, pectin, natural berry flavor.',
    suggested_use: 'Take 1 gummy 30 minutes before bedtime.',
  },
  {
    slug: 'melatonin-gummies',
    name: 'Melatonin Gummies',
    category: 'Sleep',
    tagline: 'Deep sleep, starry nights',
    description: 'Our classic melatonin formula — simple, effective, and free of synthetic dyes.',
    price_cents: 1999,
    compare_at_cents: 2499,
    currency: 'usd',
    image_url: '/products/melatonin-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Deep Sleep', 'Recovery', 'Rest'],
    ingredients: 'Melatonin (5mg), organic cane sugar, pectin, tapioca syrup, natural grape flavor.',
    suggested_use: 'Take 1 gummy 30 minutes before bedtime.',
  },
  {
    slug: 'ginger-turmeric-gummies',
    name: 'Ginger & Turmeric Gummies',
    category: 'Immunity',
    tagline: 'Ancient roots, modern recovery',
    description: 'Cold-pressed ginger root and turmeric with black pepper for enhanced absorption. Anti-inflammatory support.',
    price_cents: 2599,
    compare_at_cents: 2999,
    currency: 'usd',
    image_url: '/products/ginger-turmeric-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Anti-inflammatory', 'Immune Boost', 'Joint Support'],
    ingredients: 'Ginger root extract, turmeric extract (95% curcumin), black pepper extract, pectin, honey.',
    suggested_use: 'Take 2 gummies daily with meals.',
  },
  {
    slug: 'ashwagandha-calm-focus',
    name: 'Ashwagandha Calm & Focus',
    category: 'Stress',
    tagline: 'Balance. Stress relief. Fresh focus.',
    description: 'KSM-66 ashwagandha for steady calm and sharper focus during demanding days.',
    price_cents: 2799,
    compare_at_cents: 3299,
    currency: 'usd',
    image_url: '/products/ashwagandha-calm-focus.png',
    stock: 100,
    active: true,
    benefits: ['Balance', 'Stress Relief', 'Focus'],
    ingredients: 'KSM-66 ashwagandha root extract (600mg), L-theanine, rhodiola, pectin.',
    suggested_use: 'Take 2 gummies daily, morning or evening.',
  },
  {
    slug: 'ashwagandha-gummies',
    name: 'Ashwagandha Gummies',
    category: 'Stress',
    tagline: 'Stress, calm, focus — in one bite',
    description: 'Traditional Ayurvedic ashwagandha in a simple daily gummy.',
    price_cents: 2499,
    compare_at_cents: 2899,
    currency: 'usd',
    image_url: '/products/ashwagandha-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Stress Relief', 'Calm', 'Focus'],
    ingredients: 'Ashwagandha root extract (500mg), organic cane sugar, pectin, natural caramel flavor.',
    suggested_use: 'Take 2 gummies daily.',
  },
  {
    slug: 'energy-blend-gummies',
    name: 'Energy Blend Gummies',
    category: 'Energy',
    tagline: 'Clean energy, all-day focus',
    description: "Lion's mane, cordyceps, and B12 for clean, crash-free energy. No jitters. No caffeine crash.",
    price_cents: 2699,
    compare_at_cents: 3199,
    currency: 'usd',
    image_url: '/products/energy-blend-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Sustained Energy', 'Focus', 'No Crash'],
    ingredients: "Lion's mane mushroom, cordyceps, B12, B6, natural dates, pectin.",
    suggested_use: 'Take 2 gummies in the morning.',
  },
  {
    slug: 'elderberry-immunity',
    name: 'Elderberry Immunity',
    category: 'Immunity',
    tagline: '60-count immune defense',
    description: 'Concentrated black elderberry with vitamin C and zinc. The classic immune tonic.',
    price_cents: 2899,
    compare_at_cents: 3499,
    currency: 'usd',
    image_url: '/products/elderberry-immunity.png',
    stock: 100,
    active: true,
    benefits: ['Elderberry', 'Immune Defense', 'Antioxidant'],
    ingredients: 'Black elderberry extract, vitamin C, zinc, pectin, natural berry flavor.',
    suggested_use: 'Take 2 gummies daily during cold season.',
  },
  {
    slug: 'zinc-plus-defense',
    name: 'Zinc Plus Defense',
    category: 'Immunity',
    tagline: 'Daily supplement. Immune and recovery.',
    description: 'High-potency zinc with copper balance for immune resilience and cellular recovery.',
    price_cents: 1999,
    compare_at_cents: 2399,
    currency: 'usd',
    image_url: '/products/zinc-plus-defense.png',
    stock: 100,
    active: true,
    benefits: ['Immune Defense', 'Recovery Support', 'Vitality'],
    ingredients: 'Zinc gluconate (15mg), copper, vitamin D3, pectin.',
    suggested_use: 'Take 1 gummy daily with food.',
  },
  {
    slug: 'zinc-zinc-gummies',
    name: 'Zinc Zinc Gummies',
    category: 'Immunity',
    tagline: 'Double dose, double defense',
    description: 'A higher-potency zinc gummy for people who want concentrated immune support.',
    price_cents: 2199,
    compare_at_cents: 2599,
    currency: 'usd',
    image_url: '/products/zinc-zinc-gummies.png',
    stock: 100,
    active: true,
    benefits: ['Immune Boost', 'Zinc', 'Recovery'],
    ingredients: 'Zinc gluconate (22mg), vitamin C, pectin, natural citrus flavor.',
    suggested_use: 'Take 1 gummy daily.',
  },
  {
    slug: 'zinc-vitamin-c',
    name: 'Zinc & Vitamin C Gummies',
    category: 'Immunity',
    tagline: 'Citrus sunshine in a gummy',
    description: 'The classic immunity duo — zinc and vitamin C — in a bright, citrus-forward gummy.',
    price_cents: 2099,
    compare_at_cents: 2499,
    currency: 'usd',
    image_url: '/products/zinc-vitamin-c.png',
    stock: 100,
    active: true,
    benefits: ['Immune Boost', 'Antioxidant', 'Energy'],
    ingredients: 'Zinc, vitamin C (from acerola cherry), orange peel extract, pectin.',
    suggested_use: 'Take 2 gummies daily.',
  },
  {
    slug: 'tropical-immunity',
    name: 'Tropical Immunity Gummies',
    category: 'Immunity',
    tagline: 'Island vibes, immune support',
    description: 'Pineapple, acerola, and elderberry in a sun-bright tropical gummy kids and adults both love.',
    price_cents: 2399,
    compare_at_cents: 2799,
    currency: 'usd',
    image_url: '/products/tropical-immunity.png',
    stock: 100,
    active: true,
    benefits: ['Kid-Friendly', 'Tropical Flavor', 'Immune Support'],
    ingredients: 'Pineapple extract, acerola cherry, elderberry, vitamin C, pectin.',
    suggested_use: 'Take 2 gummies daily.',
  },
];

export function getProductBySlug(slug: string) {
  return CATALOGUE.find((p) => p.slug === slug);
}

export const CATEGORIES = ['All', 'Wellness', 'Immunity', 'Sleep', 'Stress', 'Energy'] as const;
